[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[font]
size = 19
normal = { family = "Inconsolata Nerd Font Mono", style = "Regular" }
glyph_offset = { x = 0, y = 0 }


[keyboard]
bindings = [
{ key = "Plus",  mods = "Control", action = "IncreaseFontSize"  },
{ key = "Minus", mods = "Control", action = "DecreaseFontSize"  },
{ key = "F11",   mods = "None",    action = "ToggleFullscreen"  },
]
